using PacketSerializationGenerators.Objects;

namespace PacketSerializationGenerators.Abstractions.Stringifiers;

/// <summary>
/// Represents an interface for generating logic to de/serialize properties
/// in a manner and context determined by the implementing type.
/// </summary>
public interface IPropertyStringifier
{
    /// <summary>
    /// Gets a value indicating whether the given <see cref="MyPropertySymbol"/>
    /// can be source-generated by this <see cref="IPropertyStringifier"/>.
    /// </summary>
    /// <param name="propertySymbol">The property symbol.</param>
    /// <returns>A value indicating whether the given symbol can be source-generated.</returns>
    bool CanStringify(MyPropertySymbol propertySymbol);
}
